### ISSUE TITLE
Breaking changes in upcoming Polaris 0.13

### ISSUE THREAD

**Issue by agersant** [ogarcia/docker-polaris#2]
Hello!

I am opening this issue to give a heads up that I am thinking of making the Polaris `0.13` release soon-ish (depending on how quickly I can button up the migration from Rocket to Actix). One thing that did change since `0.12.4` is the installation process on Linux. The installation directories and how they are decided have changed, to be more flexible and more standard-compliant.  I expect these changes will have some impact on the Docker setup too.

These changes affect:
- Database file location
- Web client files location
- Swagger files location
- Cache (thumbnails) files location
- Log file location
- PID file location

The previous logic to determine these locations was, in order of priority:
1. Dedicated command line argument (eg. `-w` for web client directory)
2. Some hardcoded directories within the user's $HOME (which were sourced through [app-dirs](https://github.com/AndyBarron/app-dirs-rs))

The new logic is, in order of priority:
1. Dedicated command line argument (eg. `-w` for web client directory)
2. Environment variables at compile time (listed below)
3. Some hardcoded paths within the current working directory

The corresponding compile-time environment variables are:
- `POLARIS_DB_DIR`
- `POLARIS_WEB_DIR`
- `POLARIS_SWAGGER_DIR`
- `POLARIS_CACHE_DIR`
- `POLARIS_LOG_DIR`
- `POLARIS_PID_DIR`

For reference, the supported command lines arguments are:
- `-d` or `--database` for database file
- `-w` or `--web` for web client directory
- `-s` or `--swagger` for swagger directory
- `--cache` for cache directory (`polaris` will create `thumbnails` directory inside if necessary)
- `--log` for log file
- `--pid` for pid file

The former `log` option is now `--log-level` (also a breaking change).

PR discussing these changes: https://github.com/agersant/polaris/pull/91

**Comment by ogarcia** [comment]
@agersant Thanks! When you publish the new version I'll do the changes to docker :wink:

**Comment by ahxxm** [comment]
tried simply bump version in `Makefile`,
```diff
-POLARIS_VERSION := 0.12.4                                                                                                                                                       
+POLARIS_VERSION := 0.13.0
```

It compiles but can't load database on start, then I did following steps to make it work:
- add env `- POLARIS_DB=/var/lib/polaris/.local/share/polaris/db.sqlite` to `docker-compose.yml`
- clear playlist and re-add, because all songs displayed as `null`

**Comment by agersant** [comment]
Apologies for the null songs, I forgot to document this as a breaking change. I'll update the release notes.

**Comment by ogarcia** [comment]
New version published!

Take note that now the database is, by default, in `/var/lib/polaris/db.sqlite`. See the [README](https://github.com/ogarcia/docker-polaris/blob/master/README.md) for more info and new environment variables.
