### ISSUE TITLE
Polaris docker on ARM

### ISSUE THREAD

**Issue by hajdenrajch-m** [ogarcia/docker-polaris#3]
Doesn't work.

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

**Comment by ogarcia** [comment]
Sorry, but only x64 image is provided.

**Comment by L04DB4L4NC3R** [comment]
Can you build and push official images for arm64 and arm v7 (armhf)?
In the meantime I have pushed an image for arm64 (v8) if anyone needs it:
```
docker pull angadsharma1016/polaris:arm64
```

**Comment by ogarcia** [comment]
This is duplicated of #1 

I cannot provide ARM images as long as CircleCI cannot provide a builder for them.

**Comment by L04DB4L4NC3R** [comment]
You can use `docker buildx` in circle CI. It can build images of multiple architectures without caring about the instruction set of the underlying operating system.

**Comment by ogarcia** [comment]
@L04DB4L4NC3R no, you can't. For use `buildx` in a foreing platform you must have a builder instance that supports this platform and, for now, Circle CI only supports linux/amd64 and linux/386.

You can see it in [this test](https://app.circleci.com/pipelines/bitbucket/amhairghin/circleci-tests/1/workflows/e5c9734d-8918-41e9-8f73-bd5a7bef6bad/jobs/1/parallel-runs/0/steps/0-103).

**Comment by driftywinds** [comment]
For anyone looking for this, I have started building docker images of polaris manually for arm64 and you can use it here: - [Dockerhub](https://hub.docker.com/repository/docker/driftywinds/polaris/general), [GitHub Registry](https://github.com/users/driftywinds/packages/container/package/polaris)

**Comment by lazyzyf** [comment]
> For anyone looking for this, I have started building docker images of polaris manually for arm64 and you can use it here: - [Dockerhub](https://hub.docker.com/repository/docker/driftywinds/polaris/general), [GitHub Registry](https://github.com/users/driftywinds/packages/container/package/polaris)

the two links are not available any more?

**Comment by driftywinds** [comment]
> the two links are not available any more?

I might have deleted the package while cleaning up, I'll rebuild today

**Comment by driftywinds** [comment]
> the two links are not available any more?

Please try the links again, I have updated all the builds to the latest version.

**Comment by lazyzyf** [comment]
works now, thanks.
