### ISSUE TITLE
Accessing Network Collection

### ISSUE THREAD

**Issue by hg2s** [ogarcia/docker-polaris#4]
I'm trying Polaris for the first time using Docker on Ubuntu 20.04 and want to access a mounted network volume of music on a local NAS (/media/tunes) . Sadly, Polaris is apparently unable to see or index the volume. 

The docker string I'm using is:

docker run -t -d \
--name=polaris \
-p 5050:5050 \
-v /media/tunes:/music \
-v /var/polaris/cache:/var/cache/polaris \
-v /var/polaris/data:/var/lib/polaris \
ogarcia/polaris

I'm not having any trouble accessing or logging-into Polaris. I created an Admin account and test user without a hitch. At first login Polaris asked for a music collection to be defined even though Docker includes one (-v /media/tunes:/music \). Is that normal (or necessary)? I added it anyway and it appears in the configuration. 

When I hit the Scan Now button it appears to scan for two seconds or so (On it!) and then flips back to Scan Now. No change in music collection. 

I'm assuming that it is not connecting to the music collection. Is that correct? Is there a fix? 

Thank you.

**Comment by ogarcia** [comment]
In Polaris you must look for your music in `/music` because the order `-v /media/tunes:/music` says that the `/media/tunes` folder of host is mounted on `/music` in docker.
In the other hand, make sure that any user can read `/media/tunes`.

**Comment by hg2s** [comment]
Sorry, but I don't follow. What do you mean by I have to "look for the music in /music"? 

In the Docker setup I am setting up a map to the music collection via -v /media/tunes:/music. Is that OK? 

In light of the above, why did Polaris ask me to declare a music collection when I first signed in? 

Inside Polaris, if I delete the music source (assuming the Docker mount is accepted) I still do not see any music nor is scanning initiated. 

If I enter a music source as /music (name: music) in the Collection tab under Settings, nothing happens; no scanning, etc. 

If I enter the source as /media/tunes (as it appears in Linux), still nothing (but I'm expecting this to fail). 

What am I doing wrong? 

By the way, /music/tunes is working fine with other servers like Plex, Jellyfin, Airsonic and Navidrome, all under Docker and all using a similar mount. I just can't seem to get Polaris to connect. 

-Thank you

**Comment by hg2s** [comment]
OK, I can see the tunes collection now. In Collection under Settings I set Location: /music and Name:tunes. Pressing the Scan Now button must have set it in motion because I can see the tunes collection under Music Collection > All Music. 

I can see all the folders for Artists which is the top level of the tunes collection. At the moment I cannot see any files, however. It might be scanning so I'll return later and check. Is there a progress indicator for scanning? 

-Thank you

**Comment by ogarcia** [comment]
> OK, I can see the tunes collection now. In Collection under Settings I set Location: /music and Name:tunes. Pressing the Scan Now button must have set it in motion because I can see the tunes collection under Music Collection > All Music.

Yes, that is. If you mount music in `/music` you must set in polaris that the music location is in `/music`. The name is arbitrary, you can set anything, if I set as name `My Music Collection` then when enter in Polaris I will see a folder `My Music Collection` and inside all the music subfolders.

> I can see all the folders for Artists which is the top level of the tunes collection. At the moment I cannot see any files, however. It might be scanning so I'll return later and check. Is there a progress indicator for scanning?

It have a scan button. If button says `On it` is scanning, if says `Scan now` the scan finish. The button is located under Settings -> Collection.

**Comment by hg2s** [comment]
>  It have a scan button. If button says On it is scanning, if says Scan now the scan finish. The button is located under Settings -> Collection.

I see the 'Scan now' button but it reverts from 'On It!' to 'Scan now' in two seconds. It does not stay in scanning mode for long. As an aside, the Scan Interval is set to every 30 minutes, the default value. 

At the moment I can see many more titles but many folders are still empty (apparently).

**Comment by ogarcia** [comment]
Take note that is important have your music collection perfectly tagged. Polaris uses the tags to know artist, album, etc etc

**Comment by hg2s** [comment]
All the music in the 'tunes' volume has been run through [Beets](https://beets.io/) beforehand referencing both [Discogs](https://www.discogs.com/) and [MusicBrainz](https://musicbrainz.org/) for metadata. As far as I know it's in great shape.

**Comment by hg2s** [comment]
Even though I have no indication that it's actively scanning, more tracks and albums are appearing. It's looking good.

I have to say that its **speed is impressive**. It is the **fastest server I've tested**, bar none. I'm really impressed! 

Album art is also doing very well. The vast majority of 'finds' include album artwork, something other servers miss frequently. 

I have to say that although a little sparse, it's a very worthwhile package.

**Comment by ogarcia** [comment]
If your issue is solved, please close it
