### ISSUE TITLE
Permissions issues

### ISSUE THREAD

**Issue by Eamourinho** [ogarcia/docker-polaris#6]
Any chance UID/GID can be set up as environment variables instead of hardcoded to 100/100? I'm running this off a Synology NAS and making my music dir be available to all users by default doesn't sit well with me D:

**Comment by ogarcia** [comment]
The UID/GID is set at container buildtime not in runtime, so it is not possible set the UID/GID vía variable, you must rebuild the container. To do this you can clone this repository and change [this line](https://github.com/ogarcia/docker-polaris/blob/master/.circleci/build.sh#L42) to something like this (666 is the new UID/GID):
```
addgroup -S -g 666 polaris
adduser -u 666 -S -D -H -h /var/lib/polaris -s /sbin/nologin -G polaris \
  -g polaris polaris
```
After that, simply run `make` to build image.
