### ISSUE TITLE
Error in Makefile (DOCKER_ORGANIZATION and DOCKER_IMAGE)

### ISSUE THREAD

**Issue by AscentPrime** [ogarcia/docker-polaris#8]
Hi, 
I tried to build the image but I got an error.
In the makefile : it said on line 45: Error tag "/": invalid reference format.
After a few minutes of checking, it appeared that the DOCKER_ORGANIZATION and DOCKER_IMAGE variables are not defined and should instead be CONTAINER_ORGANIZATION and CONTAINER_IMAGE.

Otherwise excellent work

**Comment by ogarcia** [comment]
Yes, you are absolutely right. When I made the last refactor I left those variables unchanged. It's fixed now.
